// src/components/Topbar.jsx
import { Bell, CaretRight, CaretDown } from '@phosphor-icons/react'
import { useState } from 'react'
import { roles } from '../mockData'
import { ProdiWordmark } from './ProdiLogo'

export default function Topbar({ breadcrumb, rolActivo, onRolChange, onNotifClick, notifCount, onLogoClick }) {
  const [rolMenuAbierto, setRolMenuAbierto] = useState(false)
  const rolActualLabel = roles.find(r => r.id === rolActivo)?.label || 'Autor'

  const rolColors = {
    autor: { bg: '#F9FCFF', text: '#0A5CF5', border: '#0A5CF5', hoverBg: '#E6EFFF' },
    coordinador: { bg: '#F0FDF4', text: '#10B981', border: '#A7F3D0', hoverBg: '#DCFCE7' },
    editor: { bg: '#FFFBEB', text: '#F59E0B', border: '#FDE68A', hoverBg: '#FEF3C7' },
    disenador: { bg: '#E7EFFE', text: '#073676', border: '#BAD2FF', hoverBg: '#D1E3FF' },
  }
  const rc = rolColors[rolActivo] || rolColors.autor

  return (
    <header
      className="fixed top-0 left-0 right-0 z-50 flex items-center justify-between px-5"
      style={{
        height: '56px',
        background: '#FFFFFF',
        borderBottom: '1px solid #E5E7EB',
        fontFamily: "'Proeduca Sans', system-ui, sans-serif",
      }}
    >
      {/* Left: Logo + Breadcrumb */}
      <div className="flex items-center gap-2">
        {/* Logo */}
        <div
          className="flex items-center mr-3"
          style={{ cursor: onLogoClick ? 'pointer' : 'default' }}
          onClick={onLogoClick}
        >
          <ProdiWordmark height={22} />
        </div>

        {/* Divider */}
        <div className="w-px h-4 bg-slate-200 mr-1" />

        {/* Breadcrumb */}
        <nav className="flex items-center gap-1">
          {breadcrumb.map((item, i) => (
            <div key={i} className="flex items-center gap-1">
              {i > 0 && <CaretRight size={12} className="text-slate-400" />}
              {item.onClick ? (
                <button
                  onClick={item.onClick}
                  className="text-sm transition-colors"
                  style={{ color: '#4B5563' }}
                  onMouseEnter={e => e.currentTarget.style.color = '#1A1A1A'}
                  onMouseLeave={e => e.currentTarget.style.color = '#4B5563'}
                >
                  {item.label}
                </button>
              ) : (
                <span className="text-sm font-medium" style={{ color: '#1A1A1A' }}>{item.label}</span>
              )}
            </div>
          ))}
        </nav>
      </div>

      {/* Right: Role selector + Bell + Avatar */}
      <div className="flex items-center gap-3">
        {/* Role selector */}
        <div className="relative">
          <button
            onClick={() => setRolMenuAbierto(!rolMenuAbierto)}
            className="flex items-center gap-2 px-3 py-1.5 rounded-lg text-xs font-medium transition-all"
            style={{
              background: rc.bg,
              color: rc.text,
              outline: `1px solid ${rc.border}`,
              outlineOffset: '-1px',
              border: 'none',
              fontFamily: "'Proeduca Sans', system-ui, sans-serif",
            }}
            onMouseEnter={e => { e.currentTarget.style.background = rc.hoverBg }}
            onMouseLeave={e => { e.currentTarget.style.background = rc.bg }}
          >
            <span>{rolActualLabel}</span>
            <CaretDown size={12} />
          </button>
          {rolMenuAbierto && (
            <div
              className="absolute right-0 top-full mt-1 w-52 rounded-xl shadow-xl py-1 z-50 animate-fade-in"
              style={{ background: '#FFFFFF', border: '1px solid #E5E7EB' }}
            >
              <div className="px-3 py-2 mb-1" style={{ borderBottom: '1px solid #F1F5F9' }}>
                <p className="text-xs font-medium" style={{ color: '#4B5563' }}>Vista de demo — cambiar rol</p>
              </div>
              {roles.map(rol => (
                <button
                  key={rol.id}
                  onClick={() => {
                    onRolChange(rol.id)
                    setRolMenuAbierto(false)
                  }}
                  className="w-full text-left px-3 py-2 transition-colors flex items-center justify-between"
                  style={{ fontFamily: "'Proeduca Sans', system-ui, sans-serif" }}
                  onMouseEnter={e => e.currentTarget.style.background = '#F8F9FA'}
                  onMouseLeave={e => e.currentTarget.style.background = 'transparent'}
                >
                  <div>
                    <p className="text-sm font-medium" style={{ color: '#1A1A1A' }}>{rol.label}</p>
                    <p className="text-xs" style={{ color: '#4B5563' }}>{rol.description}</p>
                  </div>
                  {rolActivo === rol.id && (
                    <div className="w-1.5 h-1.5 rounded-full" style={{ background: rc.text }} />
                  )}
                </button>
              ))}
            </div>
          )}
        </div>

        {/* Bell */}
        <button
          onClick={onNotifClick}
          className="relative p-2 rounded-lg transition-colors"
          onMouseEnter={e => e.currentTarget.style.background = '#F8F9FA'}
          onMouseLeave={e => e.currentTarget.style.background = 'transparent'}
        >
          <Bell size={18} style={{ color: '#4B5563' }} />
          {notifCount > 0 && (
            <span
              className="absolute -top-0.5 -right-0.5 w-4 h-4 rounded-full flex items-center justify-center text-white"
              style={{ background: '#F97316', fontSize: '10px', fontWeight: '600' }}
            >
              {notifCount}
            </span>
          )}
        </button>

        {/* Avatar */}
        <div
          className="w-8 h-8 rounded-full flex items-center justify-center text-xs font-semibold text-white"
          style={{ background: '#073676' }}
          title="Ana Lucía Martínez"
        >
          AL
        </div>
      </div>

      {/* Close dropdown on outside click */}
      {rolMenuAbierto && (
        <div className="fixed inset-0 z-40" onClick={() => setRolMenuAbierto(false)} />
      )}
    </header>
  )
}

// src/app/shared/ui/organisms/topbar/topbar.component.ts
import {
  Component,
  Input,
  Output,
  EventEmitter,
  signal,
  inject,
  OnChanges,
  ChangeDetectionStrategy,
} from '@angular/core';
import { CommonModule, NgStyle } from '@angular/common';
import { Router } from '@angular/router';
import { PhIconComponent } from '../../icons/ph-icon.component';
import { ProdiWordmarkComponent } from '../prodi-logo/prodi-logo.component';
import { roles } from '../../mock-data';

/** A single crumb rendered in the Topbar breadcrumb trail. */
export interface BreadcrumbItem {
  /** Display text. */
  label: string;
  /** Optional Angular router path to navigate to on click. */
  route?: string;
  /** Custom click handler — takes precedence over `route`. */
  onClick?: () => void;
}

interface RolColorSet {
  bg: string;
  text: string;
  border: string;
  hoverBg: string;
}

@Component({
  selector: 'app-topbar',
  standalone: true,
  imports: [CommonModule, NgStyle, PhIconComponent, ProdiWordmarkComponent],
  templateUrl: './topbar.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
/**
 * Application-wide top navigation bar.
 *
 * Displays the Prodi wordmark, a breadcrumb trail, a role-switching button,
 * and a notification bell. Emits output events instead of navigating directly
 * so that parent screens retain control over side-effects.
 */
export class TopbarComponent implements OnChanges {
  /** Breadcrumb items to render. Updated via `ngOnChanges` to reset hover state. */
  @Input() breadcrumb: BreadcrumbItem[] = [];
  /** Currently active role ID; drives button colour and dropdown selection. */
  @Input() rolActivo: string = 'autor';
  /** Number of unread notifications shown on the bell badge. */
  @Input() notifCount: number = 0;

  @Output() rolChange = new EventEmitter<string>();
  @Output() notifClick = new EventEmitter<void>();
  @Output() logoClick = new EventEmitter<void>();

  readonly roles = roles;

  rolMenuAbierto = signal(false);
  rolBtnHover = false;
  breadcrumbHover: boolean[] = [];

  readonly rolColors: Record<string, RolColorSet> = {
    autor: { bg: '#F9FCFF', text: '#0A5CF5', border: '#0A5CF5', hoverBg: '#E6EFFF' },
    coordinador: { bg: '#F0FDF4', text: '#10B981', border: '#A7F3D0', hoverBg: '#DCFCE7' },
    editor: { bg: '#FFFBEB', text: '#F59E0B', border: '#FDE68A', hoverBg: '#FEF3C7' },
    disenador: { bg: '#E7EFFE', text: '#073676', border: '#BAD2FF', hoverBg: '#D1E3FF' },
  };

  get rolActualLabel(): string {
    return this.roles.find(r => r.id === this.rolActivo)?.label ?? 'Autor';
  }

  private router = inject(Router);

  ngOnChanges(): void {
    // Keep breadcrumbHover array in sync with breadcrumb length
    this.breadcrumbHover = this.breadcrumb.map(() => false);
  }

  /** Compute inline styles for the role button, taking hover state into account. */
  getRolButtonStyle(): Record<string, string> {
    const rc = this.rolColors[this.rolActivo] ?? this.rolColors['autor'];
    const bg = this.rolBtnHover ? rc.hoverBg : rc.bg;
    return {
      background: bg,
      color: rc.text,
      border: `1px solid ${rc.border}`,
    };
  }

  /** Emit the new role and close the dropdown. */
  selectRol(rolId: string): void {
    this.rolChange.emit(rolId);
    this.rolMenuAbierto.set(false);
  }

  /** Handle a breadcrumb click: invoke custom handler or navigate by route. */
  onBreadcrumbClick(item: BreadcrumbItem): void {
    if (item.onClick) {
      item.onClick();
    } else if (item.route) {
      this.router.navigateByUrl(item.route);
    }
  }
}

<header
  class="fixed top-0 left-0 right-0 z-50 flex items-center justify-between px-5"
  style="height:56px;background:#FFFFFF;border-bottom:1px solid #E5E7EB;font-family:'Proeduca Sans',system-ui,sans-serif"
>
  <!-- Left: logo + divider + breadcrumb -->
  <div class="flex items-center gap-2">
    <div
      class="flex items-center mr-3"
      [style.cursor]="logoClick.observed ? 'pointer' : 'default'"
      (click)="logoClick.emit()"
    >
      <prodi-wordmark [height]="28" />
    </div>

    <div class="w-px h-4 bg-slate-200 mr-1"></div>

    <nav class="flex items-center gap-1">
      @for (item of breadcrumb; track item.label; let i = $index) {
        <div class="flex items-center gap-1">
          @if (i > 0) {
            <ph-icon name="CaretRight" [size]="12" style="color:#94A3B8" />
          }
          @if (item.onClick || item.route) {
            <button
              class="text-sm transition-colors bg-transparent border-0 p-0 cursor-pointer"
              [style.color]="breadcrumbHover[i] ? '#1A1A1A' : '#4B5563'"
              (click)="onBreadcrumbClick(item)"
              (mouseenter)="breadcrumbHover[i] = true"
              (mouseleave)="breadcrumbHover[i] = false"
            >
              {{ item.label }}
            </button>
          } @else {
            <span class="text-sm font-medium" style="color:#1A1A1A">{{ item.label }}</span>
          }
        </div>
      }
    </nav>
  </div>

  <!-- Right: role selector + bell + avatar -->
  <div class="flex items-center gap-3">

    <!-- Role selector -->
    <div class="relative">
      <button
        class="flex items-center gap-2 px-3 py-1.5 rounded-lg text-xs font-medium transition-all border cursor-pointer"
        [ngStyle]="getRolButtonStyle()"
        (click)="rolMenuAbierto.set(!rolMenuAbierto())"
        (mouseenter)="rolBtnHover = true"
        (mouseleave)="rolBtnHover = false"
      >
        <span>{{ rolActualLabel }}</span>
        <ph-icon name="CaretDown" [size]="12" />
      </button>

      @if (rolMenuAbierto()) {
        <div
          class="absolute right-0 top-full mt-1 w-52 rounded-xl shadow-xl py-1 z-50"
          style="background:#FFFFFF;border:1px solid #E5E7EB"
        >
          <div class="px-3 py-2 mb-1" style="border-bottom:1px solid #F1F5F9">
            <p class="text-xs font-medium" style="color:#4B5563">Vista de demo — cambiar rol</p>
          </div>
          @for (rol of roles; track rol.id) {
            <button
              class="w-full text-left px-3 py-2 transition-colors flex items-center justify-between border-0 bg-transparent cursor-pointer"
              style="font-family:'Proeduca Sans',system-ui,sans-serif"
              (click)="selectRol(rol.id)"
              (mouseenter)="$event.currentTarget.style.background='#F8F9FA'"
              (mouseleave)="$event.currentTarget.style.background='transparent'"
            >
              <div>
                <p class="text-sm font-medium" style="color:#1A1A1A">{{ rol.label }}</p>
                <p class="text-xs" style="color:#4B5563">{{ rol.description }}</p>
              </div>
              @if (rolActivo === rol.id) {
                <div
                  class="w-1.5 h-1.5 rounded-full flex-shrink-0"
                  [style.background]="rolColors[rolActivo]?.text"
                ></div>
              }
            </button>
          }
        </div>
      }
    </div>

    <!-- Bell -->
    <button
      class="relative p-2 rounded-lg transition-colors border-0 bg-transparent cursor-pointer"
      (click)="notifClick.emit()"
      (mouseenter)="$event.currentTarget.style.background='#F8F9FA'"
      (mouseleave)="$event.currentTarget.style.background='transparent'"
    >
      <ph-icon name="Bell" [size]="18" style="color:#4B5563" />
      @if (notifCount > 0) {
        <span
          class="absolute -top-0.5 -right-0.5 w-4 h-4 rounded-full flex items-center justify-center text-white"
          style="background:#F97316;font-size:10px;font-weight:600"
        >
          {{ notifCount }}
        </span>
      }
    </button>

    <!-- Avatar -->
    <div
      class="w-8 h-8 rounded-full flex items-center justify-center text-xs font-semibold text-black"
      style="background:var(--color-primary-200)"
      title="Ana Lucía Martínez"
    >
      AL
    </div>
  </div>

  <!-- Overlay to close role dropdown on outside click -->
  @if (rolMenuAbierto()) {
    <div class="fixed inset-0 z-40" (click)="rolMenuAbierto.set(false)"></div>
  }
</header>
