// src/app/shared/ui/atoms/etiqueta-bloque/etiqueta-bloque.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

const SEVERITY_CONFIG: Record<string, { background: string; color: string; iconBg: string }> = {
  Primary: {
    background: 'var(--primary-primary-100, #E7EFFE)',
    color: 'var(--primary-primary-600, #0A5CF5)',
    iconBg: 'var(--primary-primary-600, #0A5CF5)',
  },
  Secondary: {
    background: 'var(--neutrals-old-white, white)',
    color: 'var(--primary-primary-600, #0A5CF5)',
    iconBg: 'var(--primary-primary-600, #0A5CF5)',
  },
  Success: {
    background: 'var(--tag-success-background, #DCFCE7)',
    color: '#15803D',
    iconBg: '#343330',
  },
  Info: {
    background: 'var(--tag-info-background, #E0F2FE)',
    color: 'var(--tag-info-color, #0369A1)',
    iconBg: '#343330',
  },
  Warning: {
    background: 'var(--tag-warn-background, #FFEDD5)',
    color: '#C2410C',
    iconBg: '#343330',
  },
  Error: {
    background: 'var(--tag-danger-background, #FEE2E2)',
    color: 'var(--tag-danger-color, #B91C1C)',
    iconBg: '#343330',
  },
  Contrast: {
    background: 'rgba(2, 6, 23, 0.10)',
    color: 'var(--neutrals-old-Black, #090B11)',
    iconBg: '#343330',
  },
};

@Component({
  selector: 'app-etiqueta-bloque',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div
      [ngStyle]="{
        paddingLeft: '7px',
        paddingRight: '7px',
        paddingTop: '3.5px',
        paddingBottom: '3.5px',
        background: cfg.background,
        borderRadius: '6px',
        justifyContent: 'flex-start',
        alignItems: 'center',
        gap: '4px',
        display: 'inline-flex'
      }"
    >
      @if (showIcon) {
        <div [ngStyle]="{ width: '16px', height: '16px', position: 'relative' }">
          <div
            [ngStyle]="{
              width: '11.75px',
              height: '11.75px',
              left: '2.13px',
              top: '2.13px',
              position: 'absolute',
              background: cfg.iconBg
            }"
          ></div>
        </div>
      }
      <div
        [ngStyle]="{
          color: cfg.color,
          fontSize: '12px',
          fontFamily: 'Proeduca Sans',
          fontWeight: '500',
          lineHeight: '15.84px',
          wordWrap: 'break-word'
        }"
      >
        {{ label }}
      </div>
    </div>
  `,
})
/**
 * Inline comment-gravity badge rendered inside a content block.
 *
 * Shows the count of unresolved comments with a colour-coded severity indicator
 * (crítico, importante, sugerencia, nota, alertaNormativa).
 * Clicking it opens the full comment thread in the Canvas right panel.
 */
export class EtiquetaBloqueComponent {
  @Input() label: string = '';
  @Input() severity: string = 'Primary';
  @Input() showIcon: boolean = false;

  get cfg(): { background: string; color: string; iconBg: string } {
    return SEVERITY_CONFIG[this.severity] ?? SEVERITY_CONFIG['Primary'];
  }
}

// src/components/EtiquetaBloque.jsx
const SEVERITY_CONFIG = {
  Primary: {
    background: 'var(--primary-primary-100, #E7EFFE)',
    color: 'var(--primary-primary-600, #0A5CF5)',
    iconBg: 'var(--primary-primary-600, #0A5CF5)',
  },
  Secondary: {
    background: 'var(--neutrals-old-white, white)',
    color: 'var(--primary-primary-600, #0A5CF5)',
    iconBg: 'var(--primary-primary-600, #0A5CF5)',
  },
  Success: {
    background: 'var(--tag-success-background, #DCFCE7)',
    color: '#15803D',
    iconBg: '#343330',
  },
  Info: {
    background: 'var(--tag-info-background, #E0F2FE)',
    color: 'var(--tag-info-color, #0369A1)',
    iconBg: '#343330',
  },
  Warning: {
    background: 'var(--tag-warn-background, #FFEDD5)',
    color: '#C2410C',
    iconBg: '#343330',
  },
  Error: {
    background: 'var(--tag-danger-background, #FEE2E2)',
    color: 'var(--tag-danger-color, #B91C1C)',
    iconBg: '#343330',
  },
  Contrast: {
    background: 'rgba(2, 6, 23, 0.10)',
    color: 'var(--neutrals-old-Black, #090B11)',
    iconBg: '#343330',
  },
}

export default function EtiquetaBloque({ label, severity = 'Primary', showIcon = false }) {
  const cfg = SEVERITY_CONFIG[severity] || SEVERITY_CONFIG.Primary

  return (
    <div
      data-darkmode="Off"
      data-icon-={showIcon ? 'true' : 'false'}
      data-rounded="No"
      data-severity={severity}
      style={{
        paddingLeft: 7,
        paddingRight: 7,
        paddingTop: 3.5,
        paddingBottom: 3.5,
        background: cfg.background,
        borderRadius: 6,
        justifyContent: 'flex-start',
        alignItems: 'center',
        gap: 4,
        display: 'inline-flex',
      }}
    >
      {showIcon && (
        <div
          data-format="Outline"
          data-weight="Light"
          style={{ width: 16, height: 16, position: 'relative' }}
        >
          <div
            style={{
              width: 11.75,
              height: 11.75,
              left: 2.13,
              top: 2.13,
              position: 'absolute',
              background: cfg.iconBg,
            }}
          />
        </div>
      )}
      <div
        style={{
          color: cfg.color,
          fontSize: 12,
          fontFamily: 'Proeduca Sans',
          fontWeight: '500',
          lineHeight: '15.84px',
          wordWrap: 'break-word',
        }}
      >
        {label}
      </div>
    </div>
  )
}
