// src/app/components/panel-mis-pendientes/panel-mis-pendientes.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { PhIconComponent } from '../../icons/ph-icon.component';
import { misPendientes, gravedadConfig } from '../../mock-data';

const GRAVEDAD_ICON: Record<string, string> = {
  critico: 'Warning',
  importante: 'Warning',
  sugerencia: 'Lightbulb',
  nota: 'Info',
  alertaNormativa: 'ShieldWarning',
};

@Component({
  selector: 'app-panel-mis-pendientes',
  standalone: true,
  imports: [CommonModule, PhIconComponent],
  template: `
    <div class="flex flex-col gap-1">
      @for (item of pendientes; track item.id) {
        <div
          class="flex items-start gap-3 px-3 py-2.5 rounded-lg cursor-pointer transition-all"
          [ngStyle]="{
            background: hoveredItem === item.id ? '#F1F5F9' : 'transparent',
            opacity: item.activo ? 1 : 0.6
          }"
          (mouseenter)="hoveredItem = item.id"
          (mouseleave)="hoveredItem = null"
          (click)="handleClick(item)"
        >
          <!-- Gravedad icon -->
          <div
            class="w-7 h-7 rounded-full flex items-center justify-center flex-shrink-0 mt-0.5"
            [ngStyle]="{
              background: getGravedadBg(item.gravedad),
              color: getGravedadColor(item.gravedad)
            }"
          >
            <ph-icon [name]="getGravedadIcon(item.gravedad)" [size]="13" />
          </div>

          <!-- Content -->
          <div class="flex-1 min-w-0">
            <p
              class="text-sm font-medium text-slate-700 truncate"
              [ngStyle]="{ fontFamily: '\\'Proeduca Sans\\', system-ui, sans-serif' }"
            >
              {{ item.titulo }}
            </p>
            <p class="text-xs text-slate-500 mt-0.5 truncate">
              {{ item.asignatura }} · {{ item.seccion }}
            </p>
            <p class="text-xs text-slate-400 mt-0.5">{{ item.tiempo }}</p>
          </div>

          <!-- Arrow -->
          @if (item.activo) {
            <ph-icon name="ArrowRight" [size]="14" class="text-slate-400 flex-shrink-0 mt-1" />
          }
        </div>
      }

      @if (pendientes.length === 0) {
        <div class="text-sm text-slate-500 text-center py-6">
          No tienes pendientes activos.
        </div>
      }
    </div>
  `,
})
export class PanelMisPendientesComponent {
  @Input() rolActivo: string = 'autor';
  @Output() onNavigate = new EventEmitter<{ destino: string; params?: any }>();

  readonly pendientes = misPendientes;
  private readonly gc: Record<string, any> = gravedadConfig as any;

  hoveredItem: string | null = null;

  getGravedadIcon(gravedad: string): string {
    return GRAVEDAD_ICON[gravedad] ?? 'Info';
  }

  getGravedadBg(gravedad: string): string {
    return this.gc[gravedad]?.bg ?? '#F8FAFC';
  }

  getGravedadColor(gravedad: string): string {
    return this.gc[gravedad]?.color ?? '#64748B';
  }

  handleClick(item: any): void {
    if (!item.activo || !item.canvasDestino) return;
    this.onNavigate.emit({ destino: 'canvas', params: { seccion: item.canvasDestino } });
  }
}

// src/components/PanelMisPendientes.jsx
import { ArrowRight, Warning, Lightbulb, Info, ShieldWarning } from '@phosphor-icons/react'
import { misPendientes, gravedadConfig } from '../mockData'

const gravedadIcon = {
  critico: Warning,
  importante: Warning,
  sugerencia: Lightbulb,
  nota: Info,
  alertaNormativa: ShieldWarning,
}

export default function PanelMisPendientes({ rolActivo, onNavigate }) {
  const items = misPendientes

  return (
    <div
      className="flex flex-col h-full rounded-2xl overflow-hidden"
      style={{ background: '#FFFFFF', border: '1px solid #E5E7EB' }}
    >
      {/* Header */}
      <div className="px-4 py-3 flex items-center justify-between" style={{ borderBottom: '1px solid #F1F5F9' }}>
        <div>
          <p className="text-sm font-semibold" style={{ color: '#1A1A1A' }}>Mis pendientes</p>
          <p className="text-xs mt-0.5" style={{ color: '#9CA3AF' }}>
            {items.filter(i => i.activo).length} activos
          </p>
        </div>
        <div
          className="text-xs font-semibold px-2 py-0.5 rounded-md"
          style={{ background: '#FEF2F2', color: '#EF4444', fontFamily: "'Proeduca Sans', system-ui, sans-serif" }}
        >
          {items.filter(i => i.gravedad === 'critico').length} críticos
        </div>
      </div>

      {/* Items */}
      <div className="flex-1 overflow-y-auto py-1">
        {items.map((item, i) => {
          const cfg = gravedadConfig[item.gravedad] || gravedadConfig.nota
          const Icon = gravedadIcon[item.gravedad] || Info
          const clickable = item.activo && item.canvasDestino

          return (
            <div
              key={item.id}
              onClick={() => clickable && onNavigate('canvas', { seccion: item.canvasDestino })}
              className="flex items-start gap-3 px-4 py-3 transition-all group"
              style={{
                borderBottom: i < items.length - 1 ? '1px solid #F8F9FA' : 'none',
                cursor: clickable ? 'pointer' : 'default',
                opacity: item.activo ? 1 : 0.5,
              }}
              onMouseEnter={e => { if (clickable) e.currentTarget.style.background = '#F8F9FA' }}
              onMouseLeave={e => { e.currentTarget.style.background = 'transparent' }}
            >
              {/* Gravedad icon */}
              <div
                className="w-7 h-7 rounded-lg flex items-center justify-center flex-shrink-0 mt-0.5"
                style={{ background: cfg.bg, border: `1px solid ${cfg.border}` }}
              >
                <Icon size={13} style={{ color: cfg.color }} />
              </div>

              {/* Content */}
              <div className="flex-1 min-w-0">
                <p
                  className="text-sm font-medium leading-snug"
                  style={{ color: clickable ? '#1A1A1A' : '#94A3B8' }}
                >
                  {item.titulo}
                </p>
                <p className="text-xs mt-0.5 truncate" style={{ color: '#9CA3AF' }}>
                  {item.asignatura}
                </p>
                <p className="text-xs truncate" style={{ color: '#CBD5E1' }}>
                  {item.seccion}
                </p>
                <div className="flex items-center gap-2 mt-1.5">
                  <span
                    className="text-xs px-1.5 py-0.5 rounded font-medium"
                    style={{
                      background: cfg.bg,
                      color: cfg.color,
                      fontFamily: "'Proeduca Sans', system-ui, sans-serif",
                    }}
                  >
                    {cfg.label}
                  </span>
                  <span className="text-xs" style={{ color: '#CBD5E1' }}>·</span>
                  <span className="text-xs" style={{ color: '#CBD5E1' }}>{item.tiempo}</span>
                </div>
              </div>

              {/* Arrow */}
              {clickable && (
                <ArrowRight
                  size={13}
                  className="flex-shrink-0 opacity-0 group-hover:opacity-100 transition-opacity mt-1"
                  style={{ color: '#CBD5E1' }}
                />
              )}
            </div>
          )
        })}
      </div>
    </div>
  )
}
