// src/app/shared/ui/organisms/panel-notificaciones/panel-notificaciones.component.ts
import { Component, Input, Output, EventEmitter, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { PhIconComponent } from '../../icons/ph-icon.component';
import { notificaciones } from '../../mock-data';

type FilterTab = 'todas' | 'accion' | 'info';

interface Notificacion {
  id: string;
  tipo: string;
  asignatura: string;
  seccion: string;
  mensaje: string;
  tiempo: string;
  accionRequerida: boolean;
  link: string;
}

const TIPO_ICON: Record<string, string> = {
  comentarios: 'ChatCircle',
  aprobado: 'CheckCircle',
  info: 'Info',
  revision: 'Eye',
  bloqueado: 'Lock',
};

const TIPO_COLOR: Record<string, string> = {
  comentarios: '#F97316',
  aprobado: '#10B981',
  info: '#367CFF',
  revision: '#C88700',
  bloqueado: '#64748B',
};

const TIPO_BG: Record<string, string> = {
  comentarios: '#FFF7ED',
  aprobado: '#F0FDF4',
  info: '#E7EFFE',
  revision: '#FFF4DB',
  bloqueado: '#F3F4F6',
};

@Component({
  selector: 'app-panel-notificaciones',
  standalone: true,
  imports: [CommonModule, PhIconComponent],
  template: `
    <!-- Backdrop -->
    <div
      class="fixed inset-0 z-50"
      [ngStyle]="{ background: 'rgba(0,0,0,0.2)' }"
      (click)="onClose.emit()"
    ></div>

    <!-- Panel -->
    <div
      class="fixed right-0 top-0 bottom-0 z-50 flex flex-col"
      [ngStyle]="{
        width: '380px',
        background: '#FFFFFF',
        borderLeft: '1px solid #E2E8F0',
        boxShadow: '-4px 0 24px rgba(0,0,0,0.08)'
      }"
    >
      <!-- Header -->
      <div
        class="flex items-center justify-between px-5 py-4 flex-shrink-0"
        [ngStyle]="{ borderBottom: '1px solid #F1F5F9' }"
      >
        <div class="flex items-center gap-2">
          <ph-icon name="Bell" [size]="18" [ngStyle]="{ color: '#0A5CF5' }" />
          <span
            class="font-semibold text-slate-800"
            [ngStyle]="{ fontFamily: '\\'Proeduca Sans\\', system-ui, sans-serif', fontSize: '15px' }"
          >
            Notificaciones
          </span>
          @if (unreadCount > 0) {
            <span
              class="text-xs font-bold text-white px-1.5 py-0.5 rounded-full"
              [ngStyle]="{ background: '#0A5CF5', minWidth: '20px', textAlign: 'center' }"
            >
              {{ unreadCount }}
            </span>
          }
        </div>
        <button
          class="p-1.5 rounded-lg text-slate-500 transition-colors"
          [ngStyle]="closeHovered ? { background: '#F1F5F9', color: '#334155' } : {}"
          (click)="onClose.emit()"
          (mouseenter)="closeHovered = true"
          (mouseleave)="closeHovered = false"
        >
          <ph-icon name="X" [size]="18" />
        </button>
      </div>

      <!-- Filter tabs -->
      <div
        class="flex items-center gap-1 px-4 py-3 flex-shrink-0"
        [ngStyle]="{ borderBottom: '1px solid #F1F5F9' }"
      >
        @for (tab of tabs; track tab.id) {
          <button
            class="text-xs font-medium px-3 py-1.5 rounded-full transition-all"
            [ngStyle]="activeTab === tab.id
              ? { background: '#0A5CF5', color: '#FFFFFF' }
              : { background: '#F1F5F9', color: '#64748B' }"
            (click)="activeTab = tab.id"
          >
            {{ tab.label }}
          </button>
        }
      </div>

      <!-- Scrollable list grouped by asignatura -->
      <div class="flex-1 overflow-y-auto px-4 py-3">
        @for (group of groupedNotificaciones; track group.asignatura) {
          <div class="mb-4">
            <!-- Group header -->
            <p
              class="text-xs font-semibold text-slate-500 uppercase tracking-wide mb-2 px-1"
              [ngStyle]="{ fontFamily: '\\'Proeduca Sans\\', system-ui, sans-serif', letterSpacing: '0.06em' }"
            >
              {{ group.asignatura }}
            </p>

            <!-- Notifications in group -->
            @for (n of group.items; track n.id) {
              <div
                class="flex items-start gap-3 px-3 py-3 rounded-xl mb-1.5 cursor-pointer transition-all"
                [ngStyle]="{
                  background: hoveredItem === n.id ? '#F8FAFC' : 'transparent',
                  border: '1px solid ' + (hoveredItem === n.id ? '#E2E8F0' : 'transparent')
                }"
                (mouseenter)="hoveredItem = n.id"
                (mouseleave)="hoveredItem = null"
                (click)="handleNotifClick(n)"
              >
                <!-- Icon -->
                <div
                  class="w-8 h-8 rounded-full flex items-center justify-center flex-shrink-0 mt-0.5"
                  [ngStyle]="{
                    background: getTipoBg(n.tipo),
                    color: getTipoColor(n.tipo)
                  }"
                >
                  <ph-icon [name]="getTipoIcon(n.tipo)" [size]="14" />
                </div>

                <!-- Content -->
                <div class="flex-1 min-w-0">
                  <p class="text-xs font-semibold text-slate-500 mb-0.5">{{ n.seccion }}</p>
                  <p class="text-sm text-slate-700 leading-snug">{{ n.mensaje }}</p>
                  <p class="text-xs text-slate-400 mt-1">{{ n.tiempo }}</p>
                </div>

                <!-- Action required dot -->
                @if (n.accionRequerida) {
                  <div
                    class="w-2 h-2 rounded-full flex-shrink-0 mt-1.5"
                    [ngStyle]="{ background: '#0A5CF5' }"
                  ></div>
                }
              </div>
            }
          </div>
        }

        @if (groupedNotificaciones.length === 0) {
          <div class="text-sm text-slate-500 text-center py-10">
            No hay notificaciones.
          </div>
        }
      </div>
    </div>
  `,
})
/**
 * Sliding notifications drawer.
 *
 * Aggregates all system notifications, groups them by date, and allows
 * filtering by type (comentarios, aprobaciones, alertas…).
 * Navigates directly to the relevant Canvas section on item click.
 */
export class PanelNotificacionesComponent implements OnInit {
  @Output() onClose = new EventEmitter<void>();
  @Output() onNavigate = new EventEmitter<{ destino: string; params?: any }>();

  activeTab: FilterTab = 'todas';
  hoveredItem: string | null = null;
  closeHovered: boolean = false;

  readonly tabs: { id: FilterTab; label: string }[] = [
    { id: 'todas', label: 'Todas' },
    { id: 'accion', label: 'Acción requerida' },
    { id: 'info', label: 'Informativas' },
  ];

  private readonly allNotificaciones: Notificacion[] = notificaciones as Notificacion[];

  ngOnInit(): void {}

  get filteredNotificaciones(): Notificacion[] {
    if (this.activeTab === 'accion') {
      return this.allNotificaciones.filter((n) => n.accionRequerida);
    }
    if (this.activeTab === 'info') {
      return this.allNotificaciones.filter((n) => !n.accionRequerida);
    }
    return this.allNotificaciones;
  }

  get groupedNotificaciones(): { asignatura: string; items: Notificacion[] }[] {
    const map = new Map<string, Notificacion[]>();
    for (const n of this.filteredNotificaciones) {
      if (!map.has(n.asignatura)) {
        map.set(n.asignatura, []);
      }
      map.get(n.asignatura)!.push(n);
    }
    return Array.from(map.entries()).map(([asignatura, items]) => ({ asignatura, items }));
  }

  get unreadCount(): number {
    return this.allNotificaciones.filter((n) => n.accionRequerida).length;
  }

  getTipoIcon(tipo: string): string {
    return TIPO_ICON[tipo] ?? 'Bell';
  }

  getTipoColor(tipo: string): string {
    return TIPO_COLOR[tipo] ?? '#64748B';
  }

  getTipoBg(tipo: string): string {
    return TIPO_BG[tipo] ?? '#F1F5F9';
  }

  handleNotifClick(n: Notificacion): void {
    if (n.link) {
      this.onNavigate.emit({ destino: n.link });
    }
    this.onClose.emit();
  }
}

// src/components/PanelNotificaciones.jsx
import { useState } from 'react'
import { X, Warning, CheckCircle, Info, CaretRight } from '@phosphor-icons/react'
import { notificaciones } from '../mockData'

const FILTROS = [
  { id: 'todas', label: 'Todas' },
  { id: 'accion', label: 'Pendiente de mi acción' },
  { id: 'info', label: 'Informativas' },
]

const tipoIconos = {
  comentarios: { Icon: Warning, color: '#F97316', bg: '#FFF7ED' },
  aprobado: { Icon: CheckCircle, color: '#10B981', bg: '#F0FDF4' },
  info: { Icon: Info, color: '#367CFF', bg: '#E7EFFE' },
}

function agrupar(notifs) {
  const grupos = {}
  notifs.forEach(n => {
    if (!grupos[n.asignatura]) grupos[n.asignatura] = []
    grupos[n.asignatura].push(n)
  })
  return grupos
}

export default function PanelNotificaciones({ onClose, onNavigate }) {
  const [filtro, setFiltro] = useState('todas')

  const filtradas = notificaciones.filter(n => {
    if (filtro === 'accion') return n.accionRequerida
    if (filtro === 'info') return !n.accionRequerida
    return true
  })

  const grupos = agrupar(filtradas)

  return (
    <>
      {/* Backdrop */}
      <div
        className="fixed inset-0 z-50"
        style={{ background: 'rgba(15, 23, 42, 0.3)' }}
        onClick={onClose}
      />

      {/* Panel */}
      <div
        className="fixed right-0 top-0 bottom-0 z-50 flex flex-col animate-slide-in-right"
        style={{
          width: '380px',
          background: '#FFFFFF',
          boxShadow: '-8px 0 32px rgba(0,0,0,0.12)',
          fontFamily: "'Proeduca Sans', system-ui, sans-serif",
        }}
      >
        {/* Header */}
        <div
          className="flex items-center justify-between px-5 py-4 flex-shrink-0"
          style={{ borderBottom: '1px solid #E5E7EB' }}
        >
          <div>
            <h2 className="text-base font-semibold" style={{ color: '#1A1A1A' }}>Notificaciones</h2>
            <p className="text-xs mt-0.5" style={{ color: '#4B5563' }}>
              {notificaciones.filter(n => n.accionRequerida).length} requieren tu atención
            </p>
          </div>
          <button
            onClick={onClose}
            className="p-2 rounded-lg transition-colors"
            onMouseEnter={e => e.currentTarget.style.background = '#F8F9FA'}
            onMouseLeave={e => e.currentTarget.style.background = 'transparent'}
          >
            <X size={18} style={{ color: '#6B7280' }} />
          </button>
        </div>

        {/* Filters */}
        <div className="flex gap-1 px-4 py-3 flex-shrink-0" style={{ borderBottom: '1px solid #F1F5F9' }}>
          {FILTROS.map(f => (
            <button
              key={f.id}
              onClick={() => setFiltro(f.id)}
              className="text-xs font-medium px-3 py-1.5 rounded-lg transition-all"
              style={{
                background: filtro === f.id ? '#E7EFFE' : 'transparent',
                color: filtro === f.id ? '#367CFF' : '#4B5563',
                border: filtro === f.id ? '1px solid #BAD2FF' : '1px solid transparent',
              }}
            >
              {f.label}
            </button>
          ))}
        </div>

        {/* Notifications list */}
        <div className="flex-1 overflow-y-auto px-4 py-4 space-y-5">
          {Object.entries(grupos).map(([asignatura, notifs]) => (
            <div key={asignatura}>
              <p
                className="text-xs font-semibold uppercase tracking-wider mb-2"
                style={{ color: '#6B7280', fontFamily: "'Proeduca Sans', system-ui, sans-serif", letterSpacing: '0.06em' }}
              >
                {asignatura}
              </p>
              <div className="space-y-2">
                {notifs.map(notif => {
                  const { Icon, color, bg } = tipoIconos[notif.tipo] || tipoIconos.info

                  return (
                    <button
                      key={notif.id}
                      onClick={() => onNavigate(notif.link)}
                      className="w-full text-left rounded-xl p-4 transition-all group"
                      style={{
                        background: notif.accionRequerida ? '#FFFDF9' : '#F8F9FA',
                        border: notif.accionRequerida ? '1px solid #FED7AA' : '1px solid #E5E7EB',
                        borderLeft: `3px solid ${color}`,
                      }}
                      onMouseEnter={e => e.currentTarget.style.transform = 'scale(1.01)'}
                      onMouseLeave={e => e.currentTarget.style.transform = 'scale(1)'}
                    >
                      <div className="flex items-start gap-3">
                        <div
                          className="w-8 h-8 rounded-lg flex items-center justify-center flex-shrink-0 mt-0.5"
                          style={{ background: bg }}
                        >
                          <Icon size={15} style={{ color }} />
                        </div>
                        <div className="flex-1 min-w-0">
                          <p className="text-sm font-medium mb-0.5" style={{ color: '#1A1A1A' }}>{notif.seccion}</p>
                          <p className="text-sm leading-snug" style={{ color: '#4B5563' }}>{notif.mensaje}</p>
                          <div className="flex items-center gap-2 mt-2">
                            <p className="text-xs" style={{ color: '#6B7280' }}>{notif.tiempo}</p>
                            {notif.accionRequerida && (
                              <span
                                className="text-xs font-medium px-2 py-0.5 rounded"
                                style={{ background: '#FFF7ED', color: '#F97316', fontFamily: "'Proeduca Sans', system-ui, sans-serif" }}
                              >
                                Acción requerida
                              </span>
                            )}
                          </div>
                        </div>
                        <CaretRight size={14} style={{ color: '#9CA3AF' }} className="flex-shrink-0 mt-2 group-hover:text-slate-500 transition-colors" />
                      </div>
                    </button>
                  )
                })}
              </div>
            </div>
          ))}

          {filtradas.length === 0 && (
            <div className="flex flex-col items-center justify-center py-16 text-center">
              <div className="w-12 h-12 rounded-2xl flex items-center justify-center mb-3" style={{ background: '#F1F5F9' }}>
                <CheckCircle size={22} className="text-slate-400" />
              </div>
              <p className="text-sm font-medium" style={{ color: '#4B5563' }}>Sin notificaciones</p>
              <p className="text-xs mt-1" style={{ color: '#6B7280' }}>Todo al día</p>
            </div>
          )}
        </div>
      </div>
    </>
  )
}
