// src/app/shared/ui/organisms/pipeline-sidebar/pipeline-sidebar.component.ts
import {
  Component,
  Input,
  Output,
  EventEmitter,
  signal,
  HostListener,
  OnDestroy,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { PhIconComponent } from '../../../../icons/ph-icon.component';
import { StatusIndicatorComponent, toStatusKey } from '../../atoms/status-indicator/status-indicator.component';
import { TooltipComponent } from '../../atoms/tooltip/tooltip.component';
import { pipeline } from '../../../../mock-data';

const ESTADO_CLICKABLE = ['aprobado', 'borrador', 'revision', 'comentarios', 'sin_comenzar'];

@Component({
  selector: 'app-pipeline-sidebar',
  standalone: true,
  imports: [CommonModule, PhIconComponent, StatusIndicatorComponent, TooltipComponent],
  templateUrl: './pipeline-sidebar.component.html',
})
/**
 * @source      Figma — Prodi DS / Organisms / PipelineSidebar
 * @type        organism
 * @composedOf  StatusIndicatorComponent (atom), TooltipComponent (atom), PhIconComponent
 * @tokens      --pipeline-item-bg, --pipeline-item-border, --pipeline-item-active-bg, --pipeline-item-active-border
 * @figma       TBD
 *
 * Left-rail navigation for Canvas showing all pipeline sections with status indicators.
 */
export class PipelineSidebarComponent implements OnDestroy {
  @Input() seccionActiva: any = null;
  @Input() creacionData: any = null;
  @Input() esAsignaturaNueva: any = false;
  @Input() estadosSeccion: any = null;

  @Output() seccionChange = new EventEmitter<string>();

  readonly pipeline = pipeline;
  readonly toStatusKey = toStatusKey;

  temasExpandidos = signal<Record<string, boolean>>({ 'tema-1': true, 'tema-2': true });
  collapsed = signal(false);
  popoverAbierto = signal<string | null>(null);

  /** Map of temaId → info button element (for popover dismiss detection) */
  infoRefs: Map<string, HTMLElement> = new Map();

  // ── Helpers ──────────────────────────────────────────────────────────

  get temaDescMap(): Record<number, any> | null {
    const temas = this.creacionData?.resumen?.temasConDescripcion;
    if (!temas) return null;
    return Object.fromEntries(temas.map((t: any, i: number) => [i + 1, t]));
  }

  getEstado(secId: string, staticEstado: string): string {
    if (this.estadosSeccion?.[secId] !== undefined) return this.estadosSeccion[secId];
    if (!this.esAsignaturaNueva) return staticEstado;
    return 'sin_comenzar';
  }

  isClickable(estado: string): boolean {
    return ESTADO_CLICKABLE.includes(estado);
  }

  isTemaActive(etapa: any): boolean {
    return !!(this.seccionActiva && etapa.secciones && etapa.secciones.some((s: any) => s.id === this.seccionActiva));
  }

  toggleTema(id: string): void {
    this.temasExpandidos.update(prev => ({ ...prev, [id]: !prev[id] }));
  }

  handleClick(id: string, estado: string): void {
    if (!ESTADO_CLICKABLE.includes(estado)) return;
    this.seccionChange.emit(id);
  }

  getTemaEstado(etapa: any): string {
    const secEstados = etapa.secciones.map((s: any) => this.getEstado(s.id, s.estado));
    if (secEstados.some((e: string) => e === 'comentarios')) return 'comentarios';
    if (secEstados.some((e: string) => e === 'revision')) return 'revision';
    if (secEstados.some((e: string) => e === 'borrador')) return 'borrador';
    if (secEstados.every((e: string) => e === 'aprobado')) return 'aprobado';
    if (secEstados.every((e: string) => e === 'sin_comenzar')) return 'sin_comenzar';
    return 'bloqueado';
  }

  getTemaDesc(etapa: any): any | null {
    const temaNum = parseInt(etapa.id.split('-')[1], 10);
    return this.temaDescMap?.[temaNum] ?? null;
  }

  togglePopover(etapa: any, event: Event): void {
    event.stopPropagation();
    const current = this.popoverAbierto();
    this.popoverAbierto.set(current === etapa.id ? null : etapa.id);
  }

  closePopover(): void {
    this.popoverAbierto.set(null);
  }

  setInfoRef(temaId: string, el: HTMLElement | null): void {
    if (el) {
      this.infoRefs.set(temaId, el);
    } else {
      this.infoRefs.delete(temaId);
    }
  }

  // ── Progress ─────────────────────────────────────────────────────────

  get allSecciones(): any[] {
    return this.pipeline.flatMap((e: any) => e.tipo === 'tema' ? e.secciones : [e]);
  }

  get aprobadas(): number {
    return this.allSecciones.filter(s => this.getEstado(s.id, s.estado) === 'aprobado').length;
  }

  get total(): number {
    return this.allSecciones.length;
  }

  get pct(): number {
    return Math.round((this.aprobadas / this.total) * 100);
  }

  // ── Popover dismiss on outside click ─────────────────────────────────

  @HostListener('document:mousedown', ['$event'])
  onDocumentMouseDown(event: MouseEvent): void {
    if (!this.popoverAbierto()) return;
    const target = event.target as Node;

    // Check if click is inside any info button
    for (const [, el] of this.infoRefs) {
      if (el.contains(target)) return;
    }

    // Check if click is inside the popover itself
    const popoverEl = document.querySelector('.pipeline-popover');
    if (popoverEl?.contains(target)) return;

    this.popoverAbierto.set(null);
  }

  ngOnDestroy(): void {
    // HostListener cleans itself up automatically
  }
}

<!-- ── Collapsed sidebar (40px) ── -->
@if (collapsed()) {
  <aside
    class="flex flex-col items-center flex-shrink-0"
    style="width: 40px; min-width: 40px; background: var(--color-bg); border-right: 1px solid var(--color-border-neutral);"
  >
    <app-tooltip text="Expandir flujo de contenido" side="right">
      <button
        (click)="collapsed.set(false)"
        class="w-full flex items-center justify-center py-3 transition-colors"
        style="color: var(--color-text-faint);"
        (mouseenter)="$event.currentTarget.style.color = 'var(--color-text-neutral)'; $event.currentTarget.style.background = '#EEF2F7'"
        (mouseleave)="$event.currentTarget.style.color = 'var(--color-text-faint)'; $event.currentTarget.style.background = 'transparent'"
      >
        <ph-icon name="SidebarSimple" [size]="15" />
      </button>
    </app-tooltip>

    <div
      class="flex-1 flex items-center justify-center"
      style="writing-mode: vertical-rl; transform: rotate(180deg);"
    >
      <span
        class="select-none whitespace-nowrap"
        style="font-size: 10px; font-weight: 600; color: var(--color-text-faint); letter-spacing: 0.08em; text-transform: uppercase; font-family: 'Proeduca Sans', system-ui, sans-serif;"
      >
        Flujo de contenido
      </span>
    </div>
  </aside>
}

<!-- ── Expanded sidebar (208px) ── -->
@if (!collapsed()) {
  <aside
    class="flex flex-col overflow-hidden flex-shrink-0 h-full"
    style="width: 208px; min-width: 208px; background: var(--color-bg); border-right: 1px solid var(--color-border-neutral); font-family: 'Proeduca Sans', system-ui, sans-serif;"
  >
    <!-- Header -->
    <div
      class="px-3.5 py-3 flex items-center justify-between flex-shrink-0"
      style="border-bottom: 1px solid var(--color-border-neutral);"
    >
      <p style="font-size: 10px; font-weight: 600; color: var(--color-text-faint); letter-spacing: 0.06em; text-transform: uppercase; font-family: 'Proeduca Sans', system-ui, sans-serif;">
        Flujo de contenido
      </p>
      <app-tooltip text="Colapsar" side="bottom">
        <button
          (click)="collapsed.set(true)"
          class="p-1 rounded-md transition-colors"
          style="color: var(--color-text-faint);"
          (mouseenter)="$event.currentTarget.style.color = 'var(--color-text-subtle)'; $event.currentTarget.style.background = 'var(--color-bg-neutral-alt)'"
          (mouseleave)="$event.currentTarget.style.color = 'var(--color-text-faint)'; $event.currentTarget.style.background = 'transparent'"
        >
          <ph-icon name="SidebarSimple" [size]="14" />
        </button>
      </app-tooltip>
    </div>

    <!-- Nav -->
    <div class="flex-1 overflow-y-auto py-1.5 px-1.5">
      <nav class="space-y-0.5">
        @for (etapa of pipeline; track etapa.id) {

          <!-- ── Flat section (Resumen, Índice) ── -->
          @if (etapa.tipo === 'seccion') {
            <div
              (click)="handleClick(etapa.id, getEstado(etapa.id, etapa.estado))"
              class="flex items-center gap-2.5 px-3 py-2.5 transition-all"
              [style.cursor]="isClickable(getEstado(etapa.id, etapa.estado)) ? 'pointer' : 'default'"
              [style.background]="seccionActiva === etapa.id ? 'var(--color-primary-50)' : 'transparent'"
              [style.border-radius.px]="12"
              (mouseenter)="seccionActiva !== etapa.id && isClickable(getEstado(etapa.id, etapa.estado)) && ($event.currentTarget.style.background = 'var(--color-primary-50)')"
              (mouseleave)="seccionActiva !== etapa.id && ($event.currentTarget.style.background = 'transparent')"
            >
              <app-status-indicator
                [status]="toStatusKey(getEstado(etapa.id, etapa.estado))"
                variant="icon"
                size="sm"
                [noBg]="true"
              />
              <span
                class="leading-snug"
                [style.font-size]="'13px'"
                [style.font-weight]="seccionActiva === etapa.id ? 600 : 500"
                [style.color]="seccionActiva === etapa.id ? '#272A3F' : isClickable(getEstado(etapa.id, etapa.estado)) ? 'var(--color-text-neutral)' : 'var(--color-text-faint)'"
                style="font-family: 'Proeduca Sans', system-ui, sans-serif;"
              >
                {{ etapa.label }}
              </span>
              @if (seccionActiva === etapa.id) {
                <div
                  class="ml-auto w-1.5 h-1.5 rounded-full flex-shrink-0"
                  style="background: var(--color-primary-500);"
                ></div>
              }
            </div>
          }

          <!-- ── Tema group ── -->
          @if (etapa.tipo === 'tema') {
            <div class="relative">
              <!-- Tema header button -->
              <button
                (click)="toggleTema(etapa.id)"
                class="w-full flex items-center gap-2.5 px-3 py-2.5 transition-colors"
                [style.border-radius.px]="12"
                [style.background]="isTemaActive(etapa) && !temasExpandidos()[etapa.id] ? 'var(--color-primary-50)' : 'transparent'"
                (mouseenter)="$event.currentTarget.style.background = 'var(--color-primary-50)'"
                (mouseleave)="$event.currentTarget.style.background = isTemaActive(etapa) && !temasExpandidos()[etapa.id] ? 'var(--color-primary-50)' : 'transparent'"
              >
                <app-status-indicator
                  [status]="toStatusKey(getTemaEstado(etapa))"
                  variant="icon"
                  size="sm"
                  [noBg]="true"
                />
                <div class="min-w-0 text-left flex-1">
                  <p
                    class="leading-snug"
                    [style.font-size]="'13px'"
                    [style.font-weight]="600"
                    [style.color]="getTemaEstado(etapa) === 'bloqueado' || getTemaEstado(etapa) === 'sin_comenzar' ? 'var(--color-text-faint)' : '#272A3F'"
                    style="font-family: 'Proeduca Sans', system-ui, sans-serif;"
                  >
                    {{ etapa.label }}
                  </p>
                  <p
                    class="leading-tight truncate"
                    style="font-size: 11px; font-weight: 400; color: var(--color-text-faint); font-family: 'Proeduca Sans', system-ui, sans-serif;"
                  >
                    {{ etapa.labelCorto }}
                  </p>
                </div>
                <div class="flex items-center gap-1 flex-shrink-0">
                  @if (getTemaDesc(etapa)) {
                    <span
                      #infoBtn
                      (click)="togglePopover(etapa, $event)"
                      class="flex items-center justify-center w-5 h-5 rounded-md transition-colors"
                      [style.color]="popoverAbierto() === etapa.id ? 'var(--color-primary-500)' : 'var(--color-text-faint)'"
                      [style.background]="popoverAbierto() === etapa.id ? 'var(--color-ai-light)' : 'transparent'"
                      (mouseenter)="$event.stopPropagation(); $event.currentTarget.style.color = 'var(--color-primary-500)'; $event.currentTarget.style.background = 'var(--color-ai-light)'"
                      (mouseleave)="$event.stopPropagation(); popoverAbierto() !== etapa.id && ($event.currentTarget.style.color = 'var(--color-text-faint)') && ($event.currentTarget.style.background = 'transparent')"
                    >
                      <ph-icon name="Info" [size]="12" />
                    </span>
                  }
                  @if (temasExpandidos()[etapa.id]) {
                    <ph-icon name="CaretDown" [size]="12" [ngStyle]="{ color: 'var(--color-text-faint)' }" />
                  } @else {
                    <ph-icon name="CaretRight" [size]="12" [ngStyle]="{ color: 'var(--color-text-faint)' }" />
                  }
                </div>
              </button>

              <!-- TemaResumenPopover (inlined) -->
              @if (popoverAbierto() === etapa.id && getTemaDesc(etapa)) {
                <div
                  class="pipeline-popover absolute z-50 left-full ml-2 top-0 w-64 rounded-xl p-3.5"
                  style="background: var(--color-surface); border: 1px solid var(--color-border-neutral); box-shadow: 0 8px 24px rgba(0,0,0,0.12);"
                >
                  <div class="flex items-start justify-between gap-2 mb-2">
                    <span
                      class="text-xs font-semibold leading-tight"
                      style="color: var(--color-text-near-black);"
                    >
                      T{{ etapa.id.split('-')[1] }} — {{ getTemaDesc(etapa).titulo }}
                    </span>
                    <button
                      (click)="closePopover()"
                      class="flex-shrink-0 mt-0.5"
                      style="color: var(--color-text-subtle);"
                    >
                      <ph-icon name="X" [size]="12" />
                    </button>
                  </div>
                  <p class="text-xs leading-relaxed" style="color: var(--color-neutral-600);">
                    {{ getTemaDesc(etapa).descripcion }}
                  </p>
                </div>
              }

              <!-- Subsections -->
              @if (temasExpandidos()[etapa.id]) {
                <div
                  class="mt-0.5 mb-1 ml-4 space-y-0.5 pl-2"
                  style="border-left: 1.5px solid var(--color-border-neutral);"
                >
                  @for (sec of etapa.secciones; track sec.id) {
                    <div
                      (click)="handleClick(sec.id, getEstado(sec.id, sec.estado))"
                      class="flex items-center gap-2 px-2.5 py-2 transition-all"
                      [style.cursor]="isClickable(getEstado(sec.id, sec.estado)) ? 'pointer' : 'default'"
                      [style.background]="seccionActiva === sec.id ? 'var(--color-primary-50)' : 'transparent'"
                      [style.border-radius.px]="10"
                      [title]="!isClickable(getEstado(sec.id, sec.estado)) ? 'Bloqueado hasta aprobar la etapa anterior' : ''"
                      (mouseenter)="seccionActiva !== sec.id && isClickable(getEstado(sec.id, sec.estado)) && ($event.currentTarget.style.background = 'var(--color-primary-50)')"
                      (mouseleave)="seccionActiva !== sec.id && ($event.currentTarget.style.background = 'transparent')"
                    >
                      <app-status-indicator
                        [status]="toStatusKey(getEstado(sec.id, sec.estado))"
                        variant="icon"
                        size="sm"
                        [noBg]="true"
                      />
                      <span
                        class="flex-1"
                        [style.font-size]="'12px'"
                        [style.font-weight]="seccionActiva === sec.id ? 600 : 400"
                        [style.color]="seccionActiva === sec.id ? '#272A3F' : isClickable(getEstado(sec.id, sec.estado)) ? 'var(--color-neutral-600)' : 'var(--color-text-faint)'"
                        style="font-family: 'Proeduca Sans', system-ui, sans-serif;"
                      >
                        {{ sec.label }}
                      </span>
                      @if (seccionActiva === sec.id) {
                        <div
                          class="w-1.5 h-1.5 rounded-full flex-shrink-0"
                          style="background: var(--color-primary-500);"
                        ></div>
                      }
                    </div>
                  }
                </div>
              }
            </div>
          }

        }
      </nav>
    </div>

    <!-- Progress indicator -->
    <div
      class="px-3.5 py-3 flex-shrink-0"
      style="border-top: 1px solid var(--color-border-neutral); font-family: 'Proeduca Sans', system-ui, sans-serif;"
    >
      <div class="flex items-center justify-between mb-1.5">
        <p style="font-size: 10px; font-weight: 400; color: var(--color-text-faint);">Progreso</p>
        <p style="font-size: 10px; font-weight: 600; color: var(--color-text-neutral);">{{ pct }}%</p>
      </div>
      <div class="w-full h-1 rounded-full" style="background: var(--color-border-neutral);">
        <div
          class="h-full rounded-full transition-all"
          [style.width]="pct + '%'"
          style="background: var(--color-primary-500);"
        ></div>
      </div>
      <p style="font-size: 10px; font-weight: 400; color: var(--color-text-faint); margin-top: 6px;">
        {{ aprobadas }} de {{ total }} secciones aprobadas
      </p>
    </div>
  </aside>
}

// src/components/PipelineSidebar.jsx
import { useState, useRef, useEffect } from 'react'
import { CaretDown, CaretRight, SidebarSimple, Info, X } from '@phosphor-icons/react'
import { pipeline } from '../mockData'
import Tooltip from './Tooltip'
import StatusIndicator, { toStatusKey } from './StatusIndicator'

const ESTADO_CLICKABLE = ['aprobado', 'borrador', 'revision', 'comentarios', 'sin_comenzar']

function TemaResumenPopover({ tema, onClose, anchorRef }) {
  const popRef = useRef(null)

  useEffect(() => {
    const handler = (e) => {
      if (popRef.current && !popRef.current.contains(e.target) && !anchorRef.current?.contains(e.target)) {
        onClose()
      }
    }
    document.addEventListener('mousedown', handler)
    return () => document.removeEventListener('mousedown', handler)
  }, [onClose, anchorRef])

  return (
    <div
      ref={popRef}
      className="absolute z-50 left-full ml-2 top-0 w-64 rounded-xl p-3.5"
      style={{
        background: '#FFFFFF',
        border: '1px solid #E5E7EB',
        boxShadow: '0 8px 24px rgba(0,0,0,0.12)',
      }}
    >
      <div className="flex items-start justify-between gap-2 mb-2">
        <span className="text-xs font-semibold leading-tight" style={{ color: '#1A1A1A' }}>
          T{tema.numero} — {tema.titulo}
        </span>
        <button onClick={onClose} className="flex-shrink-0 mt-0.5" style={{ color: '#6B7280' }}>
          <X size={12} />
        </button>
      </div>
      <p className="text-xs leading-relaxed" style={{ color: '#4B5563' }}>
        {tema.descripcion}
      </p>
    </div>
  )
}

export default function PipelineSidebar({ seccionActiva, onSeccionChange, creacionData, esAsignaturaNueva, estadosSeccion }) {
  const [temasExpandidos, setTemasExpandidos] = useState({ 'tema-1': true, 'tema-2': true })
  const [collapsed, setCollapsed] = useState(false)
  const [popoverAbierto, setPopoverAbierto] = useState(null)
  const infoRefs = useRef({})

  const temaDescMap = creacionData?.resumen?.temasConDescripcion
    ? Object.fromEntries(creacionData.resumen.temasConDescripcion.map((t, i) => [i + 1, t]))
    : null

  const getEstado = (secId, staticEstado) => {
    if (estadosSeccion?.[secId] !== undefined) return estadosSeccion[secId]
    if (!esAsignaturaNueva) return staticEstado
    return 'sin_comenzar'
  }

  const toggleTema = (id) => setTemasExpandidos(prev => ({ ...prev, [id]: !prev[id] }))

  const handleClick = (id, estado) => {
    if (!ESTADO_CLICKABLE.includes(estado)) return
    onSeccionChange(id)
  }

  // Count approved sections for progress — use estadosSeccion for new subjects
  const allSecciones = pipeline.flatMap(e => e.tipo === 'tema' ? e.secciones : [e])
  const aprobadas = allSecciones.filter(s => getEstado(s.id, s.estado) === 'aprobado').length
  const total = allSecciones.length
  const pct = Math.round((aprobadas / total) * 100)

  if (collapsed) {
    return (
      <aside
        className="flex flex-col items-center flex-shrink-0"
        style={{ width: '40px', minWidth: '40px', background: '#F8FAFC', borderRight: '1px solid #E5E7EB' }}
      >
        <Tooltip text="Expandir flujo de contenido" side="right">
          <button
            onClick={() => setCollapsed(false)}
            className="w-full flex items-center justify-center py-3 transition-colors"
            style={{ color: '#9CA3AF' }}
            onMouseEnter={e => { e.currentTarget.style.color = '#374151'; e.currentTarget.style.background = '#EEF2F7' }}
            onMouseLeave={e => { e.currentTarget.style.color = '#9CA3AF'; e.currentTarget.style.background = 'transparent' }}
          >
            <SidebarSimple size={15} />
          </button>
        </Tooltip>
        <div
          className="flex-1 flex items-center justify-center"
          style={{ writingMode: 'vertical-rl', transform: 'rotate(180deg)' }}
        >
          <span className="select-none whitespace-nowrap" style={{ fontSize: '10px', fontWeight: 600, color: '#9CA3AF', letterSpacing: '0.08em', textTransform: 'uppercase', fontFamily: "'Proeduca Sans', system-ui, sans-serif" }}>
            Flujo de contenido
          </span>
        </div>
      </aside>
    )
  }

  return (
    <aside
      className="flex flex-col overflow-hidden flex-shrink-0 h-full"
      style={{
        width: '208px',
        minWidth: '208px',
        background: '#F8FAFC',
        borderRight: '1px solid #E5E7EB',
        fontFamily: "'Proeduca Sans', system-ui, sans-serif",
      }}
    >
      {/* Header */}
      <div className="px-3.5 py-3 flex items-center justify-between flex-shrink-0" style={{ borderBottom: '1px solid #E5E7EB' }}>
        <p style={{ fontSize: '10px', fontWeight: 600, color: '#9CA3AF', letterSpacing: '0.06em', textTransform: 'uppercase', fontFamily: "'Proeduca Sans', system-ui, sans-serif" }}>
          Flujo de contenido
        </p>
        <Tooltip text="Colapsar" side="bottom">
          <button
            onClick={() => setCollapsed(true)}
            className="p-1 rounded-md transition-colors"
            style={{ color: '#9CA3AF' }}
            onMouseEnter={e => { e.currentTarget.style.color = '#6B7280'; e.currentTarget.style.background = '#F3F4F6' }}
            onMouseLeave={e => { e.currentTarget.style.color = '#9CA3AF'; e.currentTarget.style.background = 'transparent' }}
          >
            <SidebarSimple size={14} />
          </button>
        </Tooltip>
      </div>

      {/* Nav */}
      <div className="flex-1 overflow-y-auto py-1.5 px-1.5">
        <nav className="space-y-0.5">
          {pipeline.map((etapa) => {
            // ─ Flat sections (Resumen, Índice) ─
            if (etapa.tipo === 'seccion') {
              const estado = getEstado(etapa.id, etapa.estado)
              const clickable = ESTADO_CLICKABLE.includes(estado)
              const activo = seccionActiva === etapa.id
              return (
                <div
                  key={etapa.id}
                  onClick={() => handleClick(etapa.id, estado)}
                  className="flex items-center gap-2.5 px-3 py-2.5 transition-all"
                  style={{
                    cursor: clickable ? 'pointer' : 'default',
                    background: activo ? '#F4F6FD' : 'transparent',
                    borderRadius: 12,
                  }}
                  onMouseEnter={e => { if (!activo && clickable) e.currentTarget.style.background = '#F4F6FD' }}
                  onMouseLeave={e => { if (!activo) e.currentTarget.style.background = 'transparent' }}
                >
                  <StatusIndicator status={toStatusKey(estado)} variant="icon" size="sm" noBg={true} />
                  <span
                    className="leading-snug"
                    style={{ fontSize: '13px', fontWeight: activo ? 600 : 500, color: activo ? '#272A3F' : clickable ? '#374151' : '#9CA3AF', fontFamily: "'Proeduca Sans', system-ui, sans-serif" }}
                  >
                    {etapa.label}
                  </span>
                  {activo && (
                    <div className="ml-auto w-1.5 h-1.5 rounded-full flex-shrink-0" style={{ background: '#367CFF' }} />
                  )}
                </div>
              )
            }

            // ─ Tema groups ─
            if (etapa.tipo === 'tema') {
              const expandido = !!temasExpandidos[etapa.id]
              const tieneActivo = etapa.secciones.some(s => s.id === seccionActiva)
              const secEstados = etapa.secciones.map(s => getEstado(s.id, s.estado))
              const estadoTema = secEstados.some(e => e === 'comentarios') ? 'comentarios'
                : secEstados.some(e => e === 'revision') ? 'revision'
                : secEstados.some(e => e === 'borrador') ? 'borrador'
                : secEstados.every(e => e === 'aprobado') ? 'aprobado'
                : secEstados.every(e => e === 'sin_comenzar') ? 'sin_comenzar'
                : 'bloqueado'

              const temaNum = parseInt(etapa.id.split('-')[1], 10)
              const temaDesc = temaDescMap?.[temaNum] ?? null
              const bloqueado = estadoTema === 'bloqueado' || estadoTema === 'sin_comenzar'

              return (
                <div key={etapa.id} className="relative">
                  {/* Tema header */}
                  <button
                    onClick={() => toggleTema(etapa.id)}
                    className="w-full flex items-center gap-2.5 px-3 py-2.5 transition-colors"
                    style={{
                      borderRadius: 12,
                      background: tieneActivo && !expandido ? '#F4F6FD' : 'transparent',
                    }}
                    onMouseEnter={e => e.currentTarget.style.background = '#F4F6FD'}
                    onMouseLeave={e => e.currentTarget.style.background = tieneActivo && !expandido ? '#F4F6FD' : 'transparent'}
                  >
                    <StatusIndicator status={toStatusKey(estadoTema)} variant="icon" size="sm" noBg={true} />
                    <div className="min-w-0 text-left flex-1">
                      <p className="leading-snug" style={{ fontSize: '13px', fontWeight: 600, color: bloqueado ? '#9CA3AF' : '#272A3F', fontFamily: "'Proeduca Sans', system-ui, sans-serif" }}>
                        {etapa.label}
                      </p>
                      <p className="leading-tight truncate" style={{ fontSize: '11px', fontWeight: 400, color: '#9CA3AF', fontFamily: "'Proeduca Sans', system-ui, sans-serif" }}>
                        {etapa.labelCorto}
                      </p>
                    </div>
                    <div className="flex items-center gap-1 flex-shrink-0">
                      {temaDesc && (
                        <span
                          ref={el => infoRefs.current[etapa.id] = el}
                          onClick={e => { e.stopPropagation(); setPopoverAbierto(prev => prev === etapa.id ? null : etapa.id) }}
                          className="flex items-center justify-center w-5 h-5 rounded-md transition-colors"
                          style={{
                            color: popoverAbierto === etapa.id ? '#367CFF' : '#9CA3AF',
                            background: popoverAbierto === etapa.id ? '#E7EFFE' : 'transparent',
                          }}
                          onMouseEnter={e => { e.stopPropagation(); e.currentTarget.style.color = '#367CFF'; e.currentTarget.style.background = '#E7EFFE' }}
                          onMouseLeave={e => { e.stopPropagation(); if (popoverAbierto !== etapa.id) { e.currentTarget.style.color = '#9CA3AF'; e.currentTarget.style.background = 'transparent' } }}
                        >
                          <Info size={12} />
                        </span>
                      )}
                      {expandido
                        ? <CaretDown size={12} style={{ color: '#9CA3AF' }} />
                        : <CaretRight size={12} style={{ color: '#9CA3AF' }} />
                      }
                    </div>
                  </button>

                  {popoverAbierto === etapa.id && temaDesc && (
                    <TemaResumenPopover
                      tema={temaDesc}
                      onClose={() => setPopoverAbierto(null)}
                      anchorRef={{ current: infoRefs.current[etapa.id] }}
                    />
                  )}

                  {/* Subsections */}
                  {expandido && (
                    <div className="mt-0.5 mb-1 ml-4 space-y-0.5 pl-2" style={{ borderLeft: '1.5px solid #E5E7EB' }}>
                      {etapa.secciones.map(sec => {
                        const secEstado = getEstado(sec.id, sec.estado)
                        const clickable = ESTADO_CLICKABLE.includes(secEstado)
                        const activo = seccionActiva === sec.id
                        return (
                          <div
                            key={sec.id}
                            onClick={() => handleClick(sec.id, secEstado)}
                            className="flex items-center gap-2 px-2.5 py-2 transition-all"
                            style={{
                              cursor: clickable ? 'pointer' : 'default',
                              background: activo ? '#F4F6FD' : 'transparent',
                              borderRadius: 10,
                            }}
                            title={!clickable ? 'Bloqueado hasta aprobar la etapa anterior' : undefined}
                            onMouseEnter={e => { if (!activo && clickable) e.currentTarget.style.background = '#F4F6FD' }}
                            onMouseLeave={e => { if (!activo) e.currentTarget.style.background = 'transparent' }}
                          >
                            <StatusIndicator status={toStatusKey(secEstado)} variant="icon" size="sm" noBg={true} />
                            <span
                              className="flex-1"
                              style={{
                                fontSize: '12px',
                                fontWeight: activo ? 600 : 400,
                                color: activo ? '#272A3F' : clickable ? '#4B5563' : '#9CA3AF',
                                fontFamily: "'Proeduca Sans', system-ui, sans-serif",
                              }}
                            >
                              {sec.label}
                            </span>
                            {activo && (
                              <div className="w-1.5 h-1.5 rounded-full flex-shrink-0" style={{ background: '#367CFF' }} />
                            )}
                          </div>
                        )
                      })}
                    </div>
                  )}
                </div>
              )
            }

            return null
          })}
        </nav>
      </div>

      {/* Progress indicator */}
      <div className="px-3.5 py-3 flex-shrink-0" style={{ borderTop: '1px solid #E5E7EB', fontFamily: "'Proeduca Sans', system-ui, sans-serif" }}>
        <div className="flex items-center justify-between mb-1.5">
          <p style={{ fontSize: '10px', fontWeight: 400, color: '#9CA3AF' }}>Progreso</p>
          <p style={{ fontSize: '10px', fontWeight: 600, color: '#374151' }}>{pct}%</p>
        </div>
        <div className="w-full h-1 rounded-full" style={{ background: '#E5E7EB' }}>
          <div className="h-full rounded-full transition-all" style={{ width: `${pct}%`, background: '#367CFF' }} />
        </div>
        <p style={{ fontSize: '10px', fontWeight: 400, color: '#9CA3AF', marginTop: '6px' }}>{aprobadas} de {total} secciones aprobadas</p>
      </div>
    </aside>
  )
}
