// components/PipelineSidebar.jsx
import { useState } from 'react'
import { CheckCircle2, ChevronDown, ChevronRight, Lock } from 'lucide-react'
import { pipeline } from '../mockData'

const ESTADO_CLICKABLE = ['aprobado', 'borrador', 'revision', 'comentarios']

const estadoDot = {
  borrador: '#3B82F6',
  revision: '#F59E0B',
  comentarios: '#F97316',
  aprobado: '#10B981',
  bloqueado: '#CBD5E1',
}

export default function PipelineSidebar({ seccionActiva, onSeccionChange }) {
  // Start with Tema 1 and 2 expanded since they have active sections
  const [temasExpandidos, setTemasExpandidos] = useState({ 'tema-1': true, 'tema-2': true })

  const toggleTema = (id) => setTemasExpandidos(prev => ({ ...prev, [id]: !prev[id] }))

  const handleClick = (id, estado) => {
    if (!ESTADO_CLICKABLE.includes(estado)) return
    onSeccionChange(id)
  }

  const renderSeccionIcon = (estado) => {
    if (estado === 'aprobado') return <CheckCircle2 size={12} style={{ color: '#10B981', flexShrink: 0 }} />
    if (estado === 'bloqueado') return <Lock size={11} style={{ color: '#CBD5E1', flexShrink: 0 }} />
    return (
      <div
        className="w-1.5 h-1.5 rounded-full flex-shrink-0"
        style={{ background: estadoDot[estado] || '#CBD5E1', marginTop: '1px' }}
      />
    )
  }

  // Count approved sections for progress
  const allSecciones = pipeline.flatMap(e => e.tipo === 'tema' ? e.secciones : [e])
  const aprobadas = allSecciones.filter(s => s.estado === 'aprobado').length
  const total = allSecciones.length
  const pct = Math.round((aprobadas / total) * 100)

  return (
    <aside
      className="flex flex-col h-full overflow-y-auto"
      style={{
        width: '240px',
        minWidth: '240px',
        background: '#FFFFFF',
        borderRight: '1px solid #E5E7EB',
        fontFamily: "'Inter', 'Arial', sans-serif",
      }}
    >
      <div className="px-4 pt-5 pb-3 flex-1">
        <p
          className="text-xs font-semibold uppercase tracking-wider mb-3"
          style={{ color: '#9CA3AF', fontFamily: "'Arial', sans-serif", letterSpacing: '0.08em' }}
        >
          Flujo de contenido
        </p>

        <nav className="space-y-0.5">
          {pipeline.map((etapa) => {
            // ─ Flat sections (Resumen, Índice) ─
            if (etapa.tipo === 'seccion') {
              const clickable = ESTADO_CLICKABLE.includes(etapa.estado)
              const activo = seccionActiva === etapa.id
              return (
                <div
                  key={etapa.id}
                  onClick={() => handleClick(etapa.id, etapa.estado)}
                  className="flex items-center justify-between px-2 py-2 rounded-lg transition-all"
                  style={{
                    cursor: clickable ? 'pointer' : 'default',
                    background: activo ? '#E0F4FB' : 'transparent',
                    borderLeft: activo ? '2px solid #0098CD' : '2px solid transparent',
                  }}
                  onMouseEnter={e => { if (!activo && clickable) e.currentTarget.style.background = '#F8F9FA' }}
                  onMouseLeave={e => { if (!activo) e.currentTarget.style.background = 'transparent' }}
                >
                  <div className="flex items-center gap-2">
                    {renderSeccionIcon(etapa.estado)}
                    <span
                      className="text-sm"
                      style={{
                        fontWeight: activo ? '600' : '500',
                        color: activo ? '#0098CD' : clickable ? '#374151' : '#94A3B8',
                      }}
                    >
                      {etapa.label}
                    </span>
                  </div>
                </div>
              )
            }

            // ─ Tema groups ─
            if (etapa.tipo === 'tema') {
              const expandido = !!temasExpandidos[etapa.id]
              const tieneActivo = etapa.secciones.some(s => s.id === seccionActiva)
              const estadoTema = etapa.secciones.some(s => s.estado === 'comentarios') ? 'comentarios'
                : etapa.secciones.some(s => s.estado === 'revision') ? 'revision'
                : etapa.secciones.some(s => s.estado === 'borrador') ? 'borrador'
                : etapa.secciones.every(s => s.estado === 'aprobado') ? 'aprobado'
                : 'bloqueado'

              return (
                <div key={etapa.id}>
                  {/* Tema header */}
                  <button
                    onClick={() => toggleTema(etapa.id)}
                    className="w-full flex items-center justify-between px-2 py-2 rounded-lg transition-colors"
                    style={{
                      background: tieneActivo && !expandido ? '#F0F9FF' : 'transparent',
                    }}
                    onMouseEnter={e => e.currentTarget.style.background = '#F8F9FA'}
                    onMouseLeave={e => e.currentTarget.style.background = tieneActivo && !expandido ? '#F0F9FF' : 'transparent'}
                  >
                    <div className="flex items-center gap-2 min-w-0">
                      <div
                        className="w-1.5 h-1.5 rounded-full flex-shrink-0"
                        style={{ background: estadoDot[estadoTema] || '#CBD5E1' }}
                      />
                      <div className="min-w-0 text-left">
                        <p className="text-sm font-medium leading-tight" style={{ color: '#374151' }}>
                          {etapa.label}
                        </p>
                        <p className="text-xs leading-tight truncate" style={{ color: '#9CA3AF', maxWidth: '140px' }}>
                          {etapa.labelCorto}
                        </p>
                      </div>
                    </div>
                    {expandido
                      ? <ChevronDown size={13} style={{ color: '#9CA3AF', flexShrink: 0 }} />
                      : <ChevronRight size={13} style={{ color: '#9CA3AF', flexShrink: 0 }} />
                    }
                  </button>

                  {/* Subsections */}
                  {expandido && (
                    <div className="mt-0.5 mb-1 ml-4 space-y-0.5 pl-2.5" style={{ borderLeft: '1.5px solid #E5E7EB' }}>
                      {etapa.secciones.map(sec => {
                        const clickable = ESTADO_CLICKABLE.includes(sec.estado)
                        const activo = seccionActiva === sec.id
                        return (
                          <div
                            key={sec.id}
                            onClick={() => handleClick(sec.id, sec.estado)}
                            className="flex items-center gap-2 px-2 py-1.5 rounded-md transition-all"
                            style={{
                              cursor: clickable ? 'pointer' : 'default',
                              background: activo ? '#E0F4FB' : 'transparent',
                              borderLeft: activo ? '2px solid #0098CD' : '2px solid transparent',
                              marginLeft: '-2px',
                            }}
                            title={!clickable ? 'Bloqueado hasta aprobar la etapa anterior' : undefined}
                            onMouseEnter={e => { if (!activo && clickable) e.currentTarget.style.background = '#F8F9FA' }}
                            onMouseLeave={e => { if (!activo) e.currentTarget.style.background = 'transparent' }}
                          >
                            {renderSeccionIcon(sec.estado)}
                            <span
                              className="text-xs"
                              style={{
                                fontWeight: activo ? '600' : '400',
                                color: activo ? '#0098CD' : clickable ? '#4B5563' : '#CBD5E1',
                              }}
                            >
                              {sec.label}
                            </span>
                          </div>
                        )
                      })}
                    </div>
                  )}
                </div>
              )
            }

            return null
          })}
        </nav>
      </div>

      {/* Progress indicator */}
      <div className="px-4 py-4 flex-shrink-0" style={{ borderTop: '1px solid #F1F5F9' }}>
        <div className="flex items-center justify-between mb-2">
          <p className="text-xs" style={{ color: '#9CA3AF' }}>Progreso</p>
          <p className="text-xs font-semibold" style={{ color: '#374151' }}>{pct}%</p>
        </div>
        <div className="w-full h-1.5 rounded-full" style={{ background: '#E5E7EB' }}>
          <div className="h-full rounded-full transition-all" style={{ width: `${pct}%`, background: '#0098CD' }} />
        </div>
        <p className="text-xs mt-1.5" style={{ color: '#9CA3AF' }}>{aprobadas} de {total} secciones aprobadas</p>
      </div>
    </aside>
  )
}

// src/app/components/pipeline-sidebar/pipeline-sidebar.component.ts
import {
  Component,
  Input,
  Output,
  EventEmitter,
  signal,
  HostListener,
  OnDestroy,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { PhIconComponent } from '../../icons/ph-icon.component';
import { StatusIndicatorComponent, toStatusKey } from '../status-indicator/status-indicator.component';
import { TooltipComponent } from '../tooltip/tooltip.component';
import { pipeline } from '../../mock-data';

const ESTADO_CLICKABLE = ['aprobado', 'borrador', 'revision', 'comentarios', 'sin_comenzar'];

@Component({
  selector: 'app-pipeline-sidebar',
  standalone: true,
  imports: [CommonModule, PhIconComponent, StatusIndicatorComponent, TooltipComponent],
  templateUrl: './pipeline-sidebar.component.html',
})
export class PipelineSidebarComponent implements OnDestroy {
  @Input() seccionActiva: any = null;
  @Input() creacionData: any = null;
  @Input() esAsignaturaNueva: any = false;
  @Input() estadosSeccion: any = null;

  @Output() seccionChange = new EventEmitter<string>();

  readonly pipeline = pipeline;
  readonly toStatusKey = toStatusKey;

  temasExpandidos = signal<Record<string, boolean>>({ 'tema-1': true, 'tema-2': true });
  collapsed = signal(false);
  popoverAbierto = signal<string | null>(null);

  /** Map of temaId → info button element (for popover dismiss detection) */
  infoRefs: Map<string, HTMLElement> = new Map();

  // ── Helpers ──────────────────────────────────────────────────────────

  get temaDescMap(): Record<number, any> | null {
    const temas = this.creacionData?.resumen?.temasConDescripcion;
    if (!temas) return null;
    return Object.fromEntries(temas.map((t: any, i: number) => [i + 1, t]));
  }

  getEstado(secId: string, staticEstado: string): string {
    if (this.estadosSeccion?.[secId] !== undefined) return this.estadosSeccion[secId];
    if (!this.esAsignaturaNueva) return staticEstado;
    return 'sin_comenzar';
  }

  isClickable(estado: string): boolean {
    return ESTADO_CLICKABLE.includes(estado);
  }

  toggleTema(id: string): void {
    this.temasExpandidos.update(prev => ({ ...prev, [id]: !prev[id] }));
  }

  handleClick(id: string, estado: string): void {
    if (!ESTADO_CLICKABLE.includes(estado)) return;
    this.seccionChange.emit(id);
  }

  getTemaEstado(etapa: any): string {
    const secEstados = etapa.secciones.map((s: any) => this.getEstado(s.id, s.estado));
    if (secEstados.some((e: string) => e === 'comentarios')) return 'comentarios';
    if (secEstados.some((e: string) => e === 'revision')) return 'revision';
    if (secEstados.some((e: string) => e === 'borrador')) return 'borrador';
    if (secEstados.every((e: string) => e === 'aprobado')) return 'aprobado';
    if (secEstados.every((e: string) => e === 'sin_comenzar')) return 'sin_comenzar';
    return 'bloqueado';
  }

  getTemaDesc(etapa: any): any | null {
    const temaNum = parseInt(etapa.id.split('-')[1], 10);
    return this.temaDescMap?.[temaNum] ?? null;
  }

  togglePopover(etapa: any, event: Event): void {
    event.stopPropagation();
    const current = this.popoverAbierto();
    this.popoverAbierto.set(current === etapa.id ? null : etapa.id);
  }

  closePopover(): void {
    this.popoverAbierto.set(null);
  }

  setInfoRef(temaId: string, el: HTMLElement | null): void {
    if (el) {
      this.infoRefs.set(temaId, el);
    } else {
      this.infoRefs.delete(temaId);
    }
  }

  // ── Progress ─────────────────────────────────────────────────────────

  get allSecciones(): any[] {
    return this.pipeline.flatMap((e: any) => e.tipo === 'tema' ? e.secciones : [e]);
  }

  get aprobadas(): number {
    return this.allSecciones.filter(s => this.getEstado(s.id, s.estado) === 'aprobado').length;
  }

  get total(): number {
    return this.allSecciones.length;
  }

  get pct(): number {
    return Math.round((this.aprobadas / this.total) * 100);
  }

  // ── Popover dismiss on outside click ─────────────────────────────────

  @HostListener('document:mousedown', ['$event'])
  onDocumentMouseDown(event: MouseEvent): void {
    if (!this.popoverAbierto()) return;
    const target = event.target as Node;

    // Check if click is inside any info button
    for (const [, el] of this.infoRefs) {
      if (el.contains(target)) return;
    }

    // Check if click is inside the popover itself
    const popoverEl = document.querySelector('.pipeline-popover');
    if (popoverEl?.contains(target)) return;

    this.popoverAbierto.set(null);
  }

  ngOnDestroy(): void {
    // HostListener cleans itself up automatically
  }
}

<!-- ── Collapsed sidebar (40px) ── -->
@if (collapsed()) {
  <aside
    class="flex flex-col items-center flex-shrink-0"
    style="width: 40px; min-width: 40px; background: #F8FAFC; border-right: 1px solid #E5E7EB;"
  >
    <app-tooltip text="Expandir flujo de contenido" side="right">
      <button
        (click)="collapsed.set(false)"
        class="w-full flex items-center justify-center py-3 transition-colors"
        style="color: #9CA3AF;"
        (mouseenter)="$event.currentTarget.style.color = '#374151'; $event.currentTarget.style.background = '#EEF2F7'"
        (mouseleave)="$event.currentTarget.style.color = '#9CA3AF'; $event.currentTarget.style.background = 'transparent'"
      >
        <ph-icon name="SidebarSimple" [size]="15" />
      </button>
    </app-tooltip>

    <div
      class="flex-1 flex items-center justify-center"
      style="writing-mode: vertical-rl; transform: rotate(180deg);"
    >
      <span
        class="select-none whitespace-nowrap"
        style="font-size: 10px; font-weight: 600; color: #9CA3AF; letter-spacing: 0.08em; text-transform: uppercase; font-family: 'Proeduca Sans', system-ui, sans-serif;"
      >
        Flujo de contenido
      </span>
    </div>
  </aside>
}

<!-- ── Expanded sidebar (208px) ── -->
@if (!collapsed()) {
  <aside
    class="flex flex-col overflow-hidden flex-shrink-0 h-full"
    style="width: 208px; min-width: 208px; background: #F8FAFC; border-right: 1px solid #E5E7EB; font-family: 'Proeduca Sans', system-ui, sans-serif;"
  >
    <!-- Header -->
    <div
      class="px-3.5 py-3 flex items-center justify-between flex-shrink-0"
      style="border-bottom: 1px solid #E5E7EB;"
    >
      <p style="font-size: 10px; font-weight: 600; color: #9CA3AF; letter-spacing: 0.06em; text-transform: uppercase; font-family: 'Proeduca Sans', system-ui, sans-serif;">
        Flujo de contenido
      </p>
      <app-tooltip text="Colapsar" side="bottom">
        <button
          (click)="collapsed.set(true)"
          class="p-1 rounded-md transition-colors"
          style="color: #9CA3AF;"
          (mouseenter)="$event.currentTarget.style.color = '#6B7280'; $event.currentTarget.style.background = '#F3F4F6'"
          (mouseleave)="$event.currentTarget.style.color = '#9CA3AF'; $event.currentTarget.style.background = 'transparent'"
        >
          <ph-icon name="SidebarSimple" [size]="14" />
        </button>
      </app-tooltip>
    </div>

    <!-- Nav -->
    <div class="flex-1 overflow-y-auto py-1.5 px-1.5">
      <nav class="space-y-0.5">
        @for (etapa of pipeline; track etapa.id) {

          <!-- ── Flat section (Resumen, Índice) ── -->
          @if (etapa.tipo === 'seccion') {
            <div
              (click)="handleClick(etapa.id, getEstado(etapa.id, etapa.estado))"
              class="flex items-center gap-2.5 px-3 py-2.5 transition-all"
              [style.cursor]="isClickable(getEstado(etapa.id, etapa.estado)) ? 'pointer' : 'default'"
              [style.background]="seccionActiva === etapa.id ? '#F4F6FD' : 'transparent'"
              [style.border-radius.px]="12"
              (mouseenter)="seccionActiva !== etapa.id && isClickable(getEstado(etapa.id, etapa.estado)) && ($event.currentTarget.style.background = '#F4F6FD')"
              (mouseleave)="seccionActiva !== etapa.id && ($event.currentTarget.style.background = 'transparent')"
            >
              <app-status-indicator
                [status]="toStatusKey(getEstado(etapa.id, etapa.estado))"
                variant="icon"
                size="sm"
                [noBg]="true"
              />
              <span
                class="leading-snug"
                [style.font-size]="'13px'"
                [style.font-weight]="seccionActiva === etapa.id ? 600 : 500"
                [style.color]="seccionActiva === etapa.id ? '#272A3F' : isClickable(getEstado(etapa.id, etapa.estado)) ? '#374151' : '#9CA3AF'"
                style="font-family: 'Proeduca Sans', system-ui, sans-serif;"
              >
                {{ etapa.label }}
              </span>
              @if (seccionActiva === etapa.id) {
                <div
                  class="ml-auto w-1.5 h-1.5 rounded-full flex-shrink-0"
                  style="background: #367CFF;"
                ></div>
              }
            </div>
          }

          <!-- ── Tema group ── -->
          @if (etapa.tipo === 'tema') {
            <div class="relative">
              <!-- Tema header button -->
              <button
                (click)="toggleTema(etapa.id)"
                class="w-full flex items-center gap-2.5 px-3 py-2.5 transition-colors"
                [style.border-radius.px]="12"
                [style.background]="(seccionActiva && etapa.secciones && etapa.secciones.some($any($any(s) => s.id === seccionActiva))) && !temasExpandidos()[etapa.id] ? '#F4F6FD' : 'transparent'"
                (mouseenter)="$event.currentTarget.style.background = '#F4F6FD'"
                (mouseleave)="$event.currentTarget.style.background = (seccionActiva && etapa.secciones && etapa.secciones.some($any($any(s) => s.id === seccionActiva))) && !temasExpandidos()[etapa.id] ? '#F4F6FD' : 'transparent'"
              >
                <app-status-indicator
                  [status]="toStatusKey(getTemaEstado(etapa))"
                  variant="icon"
                  size="sm"
                  [noBg]="true"
                />
                <div class="min-w-0 text-left flex-1">
                  <p
                    class="leading-snug"
                    [style.font-size]="'13px'"
                    [style.font-weight]="600"
                    [style.color]="getTemaEstado(etapa) === 'bloqueado' || getTemaEstado(etapa) === 'sin_comenzar' ? '#9CA3AF' : '#272A3F'"
                    style="font-family: 'Proeduca Sans', system-ui, sans-serif;"
                  >
                    {{ etapa.label }}
                  </p>
                  <p
                    class="leading-tight truncate"
                    style="font-size: 11px; font-weight: 400; color: #9CA3AF; font-family: 'Proeduca Sans', system-ui, sans-serif;"
                  >
                    {{ etapa.labelCorto }}
                  </p>
                </div>
                <div class="flex items-center gap-1 flex-shrink-0">
                  @if (getTemaDesc(etapa)) {
                    <span
                      #infoBtn
                      (click)="togglePopover(etapa, $event)"
                      class="flex items-center justify-center w-5 h-5 rounded-md transition-colors"
                      [style.color]="popoverAbierto() === etapa.id ? '#367CFF' : '#9CA3AF'"
                      [style.background]="popoverAbierto() === etapa.id ? '#E7EFFE' : 'transparent'"
                      (mouseenter)="$event.stopPropagation(); $event.currentTarget.style.color = '#367CFF'; $event.currentTarget.style.background = '#E7EFFE'"
                      (mouseleave)="$event.stopPropagation(); popoverAbierto() !== etapa.id && ($event.currentTarget.style.color = '#9CA3AF') && ($event.currentTarget.style.background = 'transparent')"
                    >
                      <ph-icon name="Info" [size]="12" />
                    </span>
                  }
                  @if (temasExpandidos()[etapa.id]) {
                    <ph-icon name="CaretDown" [size]="12" [ngStyle]="{ color: '#9CA3AF' }" />
                  } @else {
                    <ph-icon name="CaretRight" [size]="12" [ngStyle]="{ color: '#9CA3AF' }" />
                  }
                </div>
              </button>

              <!-- TemaResumenPopover (inlined) -->
              @if (popoverAbierto() === etapa.id && getTemaDesc(etapa)) {
                <div
                  class="pipeline-popover absolute z-50 left-full ml-2 top-0 w-64 rounded-xl p-3.5"
                  style="background: #FFFFFF; border: 1px solid #E5E7EB; box-shadow: 0 8px 24px rgba(0,0,0,0.12);"
                >
                  <div class="flex items-start justify-between gap-2 mb-2">
                    <span
                      class="text-xs font-semibold leading-tight"
                      style="color: #1A1A1A;"
                    >
                      T{{ etapa.id.split('-')[1] }} — {{ getTemaDesc(etapa).titulo }}
                    </span>
                    <button
                      (click)="closePopover()"
                      class="flex-shrink-0 mt-0.5"
                      style="color: #6B7280;"
                    >
                      <ph-icon name="X" [size]="12" />
                    </button>
                  </div>
                  <p class="text-xs leading-relaxed" style="color: #4B5563;">
                    {{ getTemaDesc(etapa).descripcion }}
                  </p>
                </div>
              }

              <!-- Subsections -->
              @if (temasExpandidos()[etapa.id]) {
                <div
                  class="mt-0.5 mb-1 ml-4 space-y-0.5 pl-2"
                  style="border-left: 1.5px solid #E5E7EB;"
                >
                  @for (sec of etapa.secciones; track sec.id) {
                    <div
                      (click)="handleClick(sec.id, getEstado(sec.id, sec.estado))"
                      class="flex items-center gap-2 px-2.5 py-2 transition-all"
                      [style.cursor]="isClickable(getEstado(sec.id, sec.estado)) ? 'pointer' : 'default'"
                      [style.background]="seccionActiva === sec.id ? '#F4F6FD' : 'transparent'"
                      [style.border-radius.px]="10"
                      [title]="!isClickable(getEstado(sec.id, sec.estado)) ? 'Bloqueado hasta aprobar la etapa anterior' : ''"
                      (mouseenter)="seccionActiva !== sec.id && isClickable(getEstado(sec.id, sec.estado)) && ($event.currentTarget.style.background = '#F4F6FD')"
                      (mouseleave)="seccionActiva !== sec.id && ($event.currentTarget.style.background = 'transparent')"
                    >
                      <app-status-indicator
                        [status]="toStatusKey(getEstado(sec.id, sec.estado))"
                        variant="icon"
                        size="sm"
                        [noBg]="true"
                      />
                      <span
                        class="flex-1"
                        [style.font-size]="'12px'"
                        [style.font-weight]="seccionActiva === sec.id ? 600 : 400"
                        [style.color]="seccionActiva === sec.id ? '#272A3F' : isClickable(getEstado(sec.id, sec.estado)) ? '#4B5563' : '#9CA3AF'"
                        style="font-family: 'Proeduca Sans', system-ui, sans-serif;"
                      >
                        {{ sec.label }}
                      </span>
                      @if (seccionActiva === sec.id) {
                        <div
                          class="w-1.5 h-1.5 rounded-full flex-shrink-0"
                          style="background: #367CFF;"
                        ></div>
                      }
                    </div>
                  }
                </div>
              }
            </div>
          }

        }
      </nav>
    </div>

    <!-- Progress indicator -->
    <div
      class="px-3.5 py-3 flex-shrink-0"
      style="border-top: 1px solid #E5E7EB; font-family: 'Proeduca Sans', system-ui, sans-serif;"
    >
      <div class="flex items-center justify-between mb-1.5">
        <p style="font-size: 10px; font-weight: 400; color: #9CA3AF;">Progreso</p>
        <p style="font-size: 10px; font-weight: 600; color: #374151;">{{ pct }}%</p>
      </div>
      <div class="w-full h-1 rounded-full" style="background: #E5E7EB;">
        <div
          class="h-full rounded-full transition-all"
          [style.width]="pct + '%'"
          style="background: #367CFF;"
        ></div>
      </div>
      <p style="font-size: 10px; font-weight: 400; color: #9CA3AF; margin-top: 6px;">
        {{ aprobadas }} de {{ total }} secciones aprobadas
      </p>
    </div>
  </aside>
}
